[project]
name = "vegan-curator"
version = "0.1.0"
description = "Newsletter curada sobre veganismo com Azure AI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agent-framework>=1.0.0b251112.post1",
]
